services:
  mysql:
    image: mysql:8.4
    container_name: basic-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - teachers_network
  redis:
    image: redis:latest
    container_name: basic-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - teachers_network
  redisinsight:
    image: redis/redisinsight:latest
    container_name: simple-redisinsight
    ports:
      - 5540:5540
    networks:
      - teachers_network
    depends_on:
      - redis
    volumes:
      - redis_insight_volume_data:/db

volumes:
  mysql_data:
    driver: local
  redis_volume_data:
  redis_insight_volume_data:

networks:
  teachers_network:
    driver: bridge